from dataclasses import dataclass
from typing import Optional, List

@dataclass
class ArchitecturePlan:
    """
    Defines the high-level architecture strategy for the application.
    Generated by the Planner before any infrastructure code.
    """
    service_type: str           # api | worker | monolith | cron | static
    scaling_strategy: str       # horizontal | queue | none
    public_exposure: bool       # Does it need an Ingress/LoadBalancer?
    requires_cache: bool        # Redis/Memcached?
    requires_queue: bool        # RabbitMQ/SQS?
    requires_database: bool     # Postgres/MySQL/Mongo?
    requires_reverse_proxy: bool # Nginx/HAProxy?
    deployment_strategy: str    # rolling | recreate | blue-green
    observability_level: str    # basic | standard | strict
    
    # Optional specifics
    detected_framework: str = "unknown"
    suggested_base_image: str = ""
