{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-agent.fullname" . }}
  labels:
    {{- include "devops-agent.labels" . | nindent 4 }}
    app: devops-agent
    version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    matchLabels:
      {{- include "devops-agent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
